### ISSUE TITLE
Get tutorials working on colab

### ISSUE THREAD

**Issue by faroit** [flekschas/jupyter-scatter-tutorial#4]
👋 @flekschas as part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/7059) I wanted to try jupyter-scatter myself and started with these notebooks. I found that they didn't seem to run out-of-the-box on colab for me, though.

- [x] a hint on the package installation is missing in the notebook itself (e.g. `!pip install ...`). I know this makes the notebook look less clean so the alternative would be to store colab-specific versions on google instead of running them from this repo.
- [x] without a specific hint about the package name, users might be inclined to install `jscatter` instead `jupyter-scatter` from pypi. Furthermore, there is a general clash in package naming for these two projects, so maybe a hint on the project website would be helpful
- [x] after installing `jupyter-scatter` the notebook runs, but no widgets are shown even for the simpliest example below. Is there some specific configuration required to make inline rendering work? (I tried `%matplotlib inline` but that didn't help). 

```python
import jscatter
import numpy as np

jscatter.plot(x=np.random.rand(500), y=np.random.rand(500))
```

**Comment by flekschas** [comment]
@faroit Good points! I'll add install instructions to the notebooks.

Regarding point 3, could you provide more details? I just tried it and everything works as expected. Did you by chance accidentally installed `jscatter` first? I noticed that uninstalling `jscatter` and then installing `jupyter-scatter` does not work in Google Colab. I had to start a new session.

![Screenshot 2024-08-25 at 12 50 08 PM](https://github.com/user-attachments/assets/b88fd7c4-c2f5-4a36-b92b-023e05ea77e0)

**Comment by faroit** [comment]
@flekschas regarding the third point. It works fine when running from scratch.

**Comment by flekschas** [comment]
@faroit I've added `pip install` instructions to the notebooks via https://github.com/flekschas/jupyter-scatter-tutorial/pull/5. I've also added a [note about the install instruction to the README](https://github.com/flekschas/jupyter-scatter-tutorial?tab=readme-ov-file#online). Does this address your other concerns?

**Comment by faroit** [comment]
@flekschas excellent. Thanks a lot!
